version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 0
    groups:
      backend-runtime:
        patterns:
          - "*"

  - package-ecosystem: npm
    directory: /web
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 0
    groups:
      control-room:
        patterns:
          - "*"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 0

  - package-ecosystem: docker-compose
    directory: /
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 0

  - package-ecosystem: docker
    directory: /aws
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 0
